services:
  - name: stubb0t
    type: web
    env: node
    region: frankfurt
    startCommand: npx turbo run stubb0t#start
    envVars:
      - key: NODE_ENV
        value: development
      - key: DEMO_STUB_TOKEN
        value: qwerty123

  - name: dashboard
    type: web
    env: node
    region: frankfurt
    startCommand: npx turbo run @tradeb0t/dashboard#start
    envVars:
      - key: DEMO_STUB_HOST
        fromService:
          name: stubb0t
          type: web
          property: host
      - key: DEMO_STUB_PORT
        value: 80
      - key: DEMO_STUB_TOKEN
        value: qwerty123
