@startuml
interface ITranslatorsCD {
    +currency(currency: Currency): Promise<D_Currency>
    +portfolio(portfolio: Portfolio): Promise<D_PortfolioPosition[]>
    +security(security: MarketInstrument): Promise<D_Security>
    +operation(operation: Operation): Promise<D_Operation>
    +operations(operations: Operation[]): Promise<D_Operation[]>
    +order(order: C_Order): Promise<D_Order>
    +orderStatus(order: C_Order): OrderStatus
    +orderOperation(order: C_Order): OperationType
}
@enduml
