@startuml
interface ITradeAlgorithm<InputsType, StateType> {
    +name: string
    +description: string
    +inputs: InputTypes
    +details: Algorithm
    +main(inputs: InputsType): Promise<AlgorithmRun<InputsType, StateType>>
    +resume(id: number): Promise<AlgorithmRun<InputsType, StateType>>
    +stop(id: number): Promise<AlgorithmRun<InputsType, StateType>>
}
@enduml