@startuml
class ExchangeTrader {
    -tradebot: TradeBot
    -watcher: ExchangeWatcher
    -logger: BotLogger
    -exchangeClient: ExchangeClient
    +scheduleAction(action: Function, date: Date): Job
    +scheduleOrder(date: Date, order: OrderDetails, run_id?: number | null): Job
    +sendOrder(__0: OrderDetails, run_id?: number | null): Promise<OrderStatus>
}

@enduml
