@startuml

class BotApi {
    -_tradeBot: TradeBot
    -_restServer: Express
    -_webSocketServer: Server<DefaultEventsMap, DefaultEventsMap, DefaultEventsMap, any>
    -_httpServer: http.Server
    -configureServers(): Promise<void>
    +webSocketServer: Server<DefaultEventsMap, DefaultEventsMap, DefaultEventsMap, any>
    +httpServer: http.Server
}
class BotLogger {
    -tradebot: TradeBot
    -botApi: BotApi
    -logger: Logger
    -_lastLogs: string[]
    -createLogsDirIfNotExist(): void
    +updateLastLogs(message: string): void
    +getLastLogs(): string
    +log(message: string): void
}

class BotAuth {
    -botToken: string
    +authByToken(token: string): boolean
    +authByRequest(request: IHttpHeadersCarrier): boolean
}
@enduml
